#mail
#to:Bob Hamilton
#from:Seymour Krei
#date:20110224
Bob,

I'm very busy with corporate trying to make an argument for the continued existence of the lab.

I know you're aware of the very real security implications if something were to go wrong, and I certainly know the board do. Can you please whip up a slideshow that goes over all the precautions we have taken to safeguard the company from these entities gaining access to the outside world?

It's fairly urgent!


Much appreciated,
- Seymour

