#mail
#to:Bob Hamilton
#from:David Ridect
#date:20110314
Bob,

I'm worried about the physical security of the lab - yesterday an IT bean-counter was nosing around in there, complaining about desktop licenses and whether we'd bought all the equipment from their preferred supplier (yeesh!)

Not so much of a normal security threat, but given how volatile this stuff is, shouldn't we at least have a warning sign on the door?