#mail
#to:Bob Hamilton
#from:Peter Kerr
#date:20110216
Fwd: Limericks

Just thought you might like this. :-)

&gt; -----Original Message-----
&gt; From: David Ridect [mailto:davidr@aai.com]
&gt; Sent: 03 March 2011 1:31 PM
&gt; To: Peter Kerr
&gt; Cc: Seymour Krei
&gt; Subject: Fwd: Limericks
&gt;
&gt;If you catch a Chinchilla in Chile
&gt;And cut off its beard, willy-nilly
&gt;You can honestly say
&gt;That you have just made
&gt;A Chilean Chinchilla's chin chilly
&gt;
&gt;-------------------------------------------
&gt;
&gt;The sea captain's tender young bride
&gt;fell into the bay at low tide,
&gt;You could tell by her squeals,
&gt;that some of the eels
&gt;had discovered a good place to hide.
&gt;
&gt;-------------------------------------------
&gt;
&gt;There once was a maid from Madras
&gt;Who had a magnificent ass.
&gt;Not rounded and pink,
&gt;as you'd possibly think;
&gt;It was gray, had long ears, and ate grass.
&gt;
&gt;
&gt; - David