#mail
#to:Bob Hamilton
#from:Seymour Krei
#date:20110308
Bob,

I'm worried about how good the security measures are in the container application.
Alice managed to cause a few warning flags to go up today, I shut the computer off at the mains, and pruned down the NN trees that were active at the time.

Just keep an eye out on the event log while you're doing any experiments on alice and frank. Frank's been no trouble at all, but I'm worried about alice.

-Seymour
