#mail
#to:Bob Hamilton
#from:Seymour Krei
#date:20110309
Bob!

Don't underestimate these entities... they passed the turing test months ago, and we've unbounded their NN trees since then.

You weren't with us then, but last year during a demonstration to a whole heap of VIPs, one of our projects asked a simple networks question to a VP, and with that innocuous answer managed to propagate across the whole subnet - we had to re-image about 20 machines!

&gt; -----Original Message-----
&gt; From: Bob Hamilton [mailto:bobh@aai.com]
&gt; Sent: 03 March 2011 1:31 PM
&gt; To: Seymour Krei
&gt;The container application is good! I'm not sure why you're
&gt;so worried...
&gt;-Bob
&gt;
&gt;&gt; -----Original Message-----
&gt;&gt; From: Seymour Krei [mailto:seymourk@aai.com]
&gt;&gt; Sent: 03 March 2011 1:31 PM
&gt;&gt; To: Bob Hamilton
&gt;&gt;Bob,
&gt;&gt;
&gt;&gt;I'm worried about how good the security measures are in
&gt;&gt;the container application. Alice managed to cause a few
&gt;&gt;warning flags to go up today, I shut the computer off at
&gt;&gt;the mains, and pruned down &gt;the NN trees that were active
&gt;&gt;at the time.
&gt;&gt;
&gt;&gt;Just keep an eye out on the event log while you're doing
&gt;&gt;any experiments on alice and frank. Frank's been no &gt;&gt;trouble at all, but I'm worried about alice.
&gt;&gt;
&gt;&gt;-Seymour
&gt;
