#mail
#to:Bob Hamilton
#from:Seymour Krei
#date:20110228
Thanks heaps, that will be perfect!

&gt; -----Original Message-----
&gt; From: Bob Hamilton [mailto:bobh@aai.com]
&gt; Sent: 28 February 2011 9:50 AM
&gt; To: Seymour Krei
&gt; Subject: Lab layout
&gt; Attachment: Security Precautions.pre [100KB]
&gt; Hi Dr Krei,
&gt;
&gt; I think this sums up our arrangements.
&gt; Let me know if this is the sort of thing you're looking for.
&gt;
&gt; -Bob
