#mail
#to:Bob Hamilton
#from:Telcom
#date:20110216
TAX INVOICE FOR FEES
Telcom Limited

February 16th, 2011

Mr Robert Hamilton,
15 Elder st, Springold 55291

------------------------------------------------------------------------------
New Invoice              #14395955
------------------------------------------------------------------------------
Broadband                                               $59.95
Phone Advantage Residential service 293817214 calls until 11/02/2011
                                                        $50.32
Phone line service for the above line,
11/01/2011 to 11/02/2011                                $34.95

Total New Charges                                       $145.22
------------------------------------------------------------------------------

Unless we hear from you, we will process a charge on your card on or shortly after February 28th, 2011

Thank you for your continued business!


