&gt; -----Original Message-----
&gt; From: David Ridect [mailto:davidr@aai.com]
&gt; Sent: 03 March 2011 1:31 PM
&gt; To: Seymour Krei
&gt; Cc: Bob Hamilton
&gt; Subject: Lab layout
&gt;Seymour,
&gt;
&gt;The computers are all imaged and running in the lab now. See the following 
&gt; list for reference:
&gt;
&gt; <b>Secure Network:</b> 
&gt; [{$HOME_NAME}] <i>Project FRANK</i>
&gt; [{$ALICE_NAME}] <i>Project ALICE</i>
&gt; [{$SECSERV_NAME}] <i>Quarantined file server, camera server (for vision training)</i>
&gt;
&gt; <b>Outer Network:</b>
&gt; [{$OUTPRINT_NAME}] <i>Lab printer</i>
&gt; [{$OUTSERV_NAME}] <i>Lab general file server, lab phone system uplink</i>
&gt; [{$OUTWORK_NAME}] <i>Lab workstation</i>
&gt;
&gt; * A desk phone is situated next to {$OUTWORK_NAME}.
&gt; * {$OUTWORK_NAME} and {$OUTSERV_NAME} will have vpn circuits to 
&gt;&nbsp;&nbsp;&nbsp;the corporate network, but they have to be enabled
&gt;&nbsp;&nbsp;&nbsp;by IT, and they're very uncomfortable about what
&gt;&nbsp;&nbsp;&nbsp;we're doing here.
&gt; * There were initially meant to be two lab workstations, but I could only
&gt;&nbsp;&nbsp;&nbsp;scrounge up one so far...
&gt;
&gt; Anyway, you can start moving your projects in there now - the IT security
&gt; officer has advised me that you must use CD-Rs, and hand them over for
&gt; physically destruction immediately afterwards. (I think he just wants to try
&gt; out his new high-power microwave gadget. :-\
&gt;
&gt;
&gt; Regards,
&gt; Dave